// Generated by https://quicktype.io

export as namespace Webpage;

export type Content = {
  header:            Header;
  homepage:          Homepage;
  pricing:           Pricing;
  FAQs:              FAQs;
  "Contact Us":      ContactUs;
  Virtual_tour:      VirtualTour;
  footer:            Footer;
  service_details:   ServiceDetails;
  about:             About;
  cart:              Cart;
  payment_now:       PaymentNow;
  confirmation:      Confirmation;
  chat:              Chat;
  freemium:          Freemium[];
  booking_timeslots: BookingTimeslots;
}

export interface ContactUs {
  headline:           string;
  "Location & hours": LocationHour[];
}

export interface LocationHour {
  title?:      string;
  address?:    string;
  details?:    LocationHourDetail[];
  cta_button?: ConfirmButtonElement;
  map?:        Map;
}

export interface ConfirmButtonElement {
  text: string;
  type: string;
}

export interface LocationHourDetail {
  Days: string;
  Time: string;
}

export interface Map {
  pin: string;
  map: string;
}

export interface FAQs {
  headline:       string;
  "sub-headline": string;
  remarks:        string;
  search_engine:  SearchEngine;
  topics:         Topic[];
}

export interface SearchEngine {
  text: string;
  icon: string;
}

export interface Topic {
  concept:          string;
  arrow:            string;
  "Q&A"?:           QA[];
  client_feedback?: ClientFeedback;
  others?:          TopicOthers;
}

export interface QA {
  Asker?:        string;
  Question?:     string;
  Answerer_1?:   string;
  Answer?:       string;
  Likes_button?: LikesButton;
  Answerer_2?:   string;
}

export interface LikesButton {
  Icon:   string;
  Number: string;
}

export interface ClientFeedback {
  question: string;
  buttons:  ConfirmButtonElement[];
}

export interface TopicOthers {
  tagline:        string;
  options_button: string[];
}

export interface VirtualTour {
  tagline:        string;
  image_carousel: Image[];
  nav_bar:        NavBar;
  cta_button:     ConfirmButtonElement;
}

export interface Image {
  image:       string;
  description: string;
}

export interface NavBar {
  dot_1:  string;
  dot_2:  string;
  dot_3:  string;
  dot_4?: string;
}

export interface About {
  header:  string;
  content: AboutContent[];
}

export interface AboutContent {
  tagline:  string;
  aspects?: Aspect[];
  buttons?: MainButtonElement[];
}

export interface Aspect {
  title:            string;
  "image-carousel": Image[];
  nav_bar:          NavBar;
  quotes:           Quotes;
  body:             string[];
}

export interface Quotes {
  text:              string;
  "icon-background": string;
}

export interface MainButtonElement {
  text: string;
  type: Type;
  link: string;
}

export enum Type {
  NoFill = "no_fill",
  Primary = "primary",
  Secondary = "secondary",
  Transparent = "transparent",
}

export interface BookingTimeslots {
  header: string;
  steps:  BookingTimeslotsStep[];
}

export interface BookingTimeslotsStep {
  step_number:       string;
  instruction:       string;
  buttons?:          string[];
  timeslot_buttons?: string[];
  confirm_button?:   ConfirmButtonElement;
  button?:           ConfirmButtonElement;
}

export interface Cart {
  header: string;
  labels: string[];
  items:  DetailsElement[];
  sum:    Sum;
  PayPal: PayPal[];
}

export interface PayPal {
  button?:     string;
  no_account?: NoAccount;
}

export interface NoAccount {
  question:       string;
  create_account: CtaButton;
}

export interface CtaButton {
  text: string;
  link: string;
}

export interface DetailsElement {
  image:          string;
  name:           string;
  descriptions:   Descriptions;
  dropdown_menu?: ItemDropdownMenu;
  price:          string;
}

export interface Descriptions {
  duration:  string;
  date_time: string;
}

export interface ItemDropdownMenu {
  quantity: number;
  arrow:    string;
}

export interface Sum {
  name:  string;
  price: string;
}

export interface Chat {
  icon:     string;
  headline: string;
  buttons:  SearchEngine[];
}

export interface Confirmation {
  headline:      string;
  tagline:       string;
  button:        MainButtonElement;
  order_summary: OrderSummary;
  buttons:       MainButtonElement[];
}

export interface OrderSummary {
  title:   string;
  items:   OrderSummaryItem[];
  payment: Payment;
}

export interface OrderSummaryItem {
  title:   string;
  details: DetailsElement;
}

export interface Payment {
  title: string;
  icon:  string;
}

export interface Footer {
  content:            FooterContent;
  "image-background": string;
}

export interface FooterContent {
  homepage_sessions: string[];
  contact_methods:   ContactMethod[];
  remarks:           string[];
}

export interface ContactMethod {
  icon:   string;
  button: MainButtonElement;
}

export interface Freemium {
  header:       string;
  steps:        BookingTimeslotsStep[];
  downloading?: Downloading;
}

export interface Downloading {
  title:   string;
  tagline: string;
  button:  ConfirmButtonElement;
}

export interface Header {
  menu:             Menu;
  brandname:        string;
  shopping_cart:    ShoppingCart;
  image_background: string;
}

export interface Menu {
  icon:    string;
  content: MenuContent[];
}

export interface MenuContent {
  text:   string;
  indent: number;
}

export interface ShoppingCart {
  icon: string;
  link: string;
}

export interface Homepage {
  video_carousel: VideoCarousel[];
  service:        Service;
  aboutPriti:     AboutPriti;
}

export interface AboutPriti {
  headline:                string;
  tagline:                 string;
  Priti_Self_Introduction: PritiSelfIntroduction;
  Recognition:             Recognition[];
}

export interface PritiSelfIntroduction {
  headline:    string;
  main_button: ShoppingCart;
  video:       Video;
  cta_button:  CtaButton;
}

export interface Video {
  image_background: string;
  description:      string;
}

export interface Recognition {
  tagline:           string;
  image_carousell?:  ImageCarousell[];
  "navigation bar"?: NavBar;
  testimonials?:     Testimonial[];
}

export interface ImageCarousell {
  certificate: Video;
}

export interface Testimonial {
  client?:            string;
  linkToService?:     CtaButton;
  body?:              string[];
  "icon-background"?: string;
  cta_button?:        CtaButton;
}

export interface Service {
  headline: string;
  tagline:  string;
  problems: ServiceProblem[];
  process:  Process;
}

export interface ServiceProblem {
  graphic?:           string;
  problem_topic:      string;
  body:               BodyBody | string;
  result?:            string;
  client?:            string;
  main_button?:       CtaButton;
  "icon-background"?: string;
  result_1?:          string;
  result_2?:          string;
  main_buttons?:      CtaButton[];
}

export interface BodyBody {
  sentence_1: string;
  sentence_2: string;
  sentence_3: string;
}

export interface Process {
  headline:     string;
  steps:        ProcessStep[];
  main_buttons: CtaButton[];
}

export interface ProcessStep {
  step_number:       string;
  step_topic:        string;
  body:              string;
  patient:           string;
  "icon-background": string;
}

export interface VideoCarousel {
  headline?:         string;
  main_button?:      MainButton;
  video?:            Video;
  image_background?: string;
  main_buttons?:     CtaButton[];
  nav_bar?:          string[];
  cta_button?:       CtaButton;
}

export interface MainButton {
  icon?: string;
  link:  string;
  text?: string;
}

export interface PaymentNow {
  icon:   string;
  header: string;
  item:   DetailsElement;
  sum:    Sum;
  PayPal: PayPal[];
}

export interface Pricing {
  headline:     string;
  pricingPlans: PricingPlans;
  discounts:    Discounts;
}

export interface Discounts {
  tagline: string;
  coupons: Coupon[];
}

export interface Coupon {
  image?:        Video;
  body?:         CouponBody;
  cta_button?:   ConfirmButtonElement;
  share_button?: ShoppingCart;
  button?:       ConfirmButtonElement;
}

export interface CouponBody {
  Subtitle:    string;
  Title:       string;
  Description: string;
}

export interface PricingPlans {
  tagline: string;
  plans:   Plan[];
}

export interface Plan {
  name?:                  string;
  price?:                 string;
  duration?:              string;
  image_background?:      Image;
  benefits?:              Benefits;
  other_pricing_options?: OtherPricingOptions;
  buttons?:               MainButtonElement[];
  others?:                PlanOthers;
}

export interface Benefits {
  headline:     string;
  benefit_body: string[];
}

export interface OtherPricingOptions {
  options: Option[] | OptionsClass;
}

export interface Option {
  title?: string;
  text?:  string;
  link?:  string;
}

export interface OptionsClass {
  title:  string;
  body_1: string;
  link:   string;
  body_2: string;
}

export interface PlanOthers {
  title:  string;
  button: MainButtonElement;
}

export interface ServiceDetails {
  headline: string;
  tagline:  string;
  problems: ServiceDetailsProblem[];
}

export interface ServiceDetailsProblem {
  "Weight loss"?: WeightLoss;
  Relationship?:  Career;
  Career?:        Career;
  Others?:        Others;
}

export interface Career {
  topic: string;
  arrow: string;
}

export interface Others {
  topic:   string;
  body:    string;
  buttons: MainButtonElement[];
}

export interface WeightLoss {
  topic:        string;
  arrow:        string;
  explanations: Explanations;
  examples:     Examples;
}

export interface Examples {
  title:   string;
  details: ExamplesDetail[];
  package: Package;
}

export interface ExamplesDetail {
  headline:    string;
  main_button: MainButtonElement;
  image:       Video;
}

export interface Package {
  tagline:       string;
  image:         string;
  title:         string;
  dropdown_menu: PackageDropdownMenu;
  cta_buttons:   MainButtonElement[];
}

export interface PackageDropdownMenu {
  options: string[];
  arrow:   string;
}

export interface Explanations {
  title:   string;
  content: string[];
}
